Import('com_env')
#######################################################
# Compile for bootanimation
# Copyright Insta360 @ 2016 - 2025
#######################################################

import config

src = Glob('*.cpp')

#src += [config.LIBLOG + '/logd_write.c']
#src += [config.LIBLOG + '/log_event_write.c']
#src += [config.LIBLOG + '/logprint.c']
#src += [config.LIBLOG + '/event_tag_map.c']
#src += [config.LIBLOG + '/log_time.cpp']
#src += [config.LIBLOG + '/log_wrapper.cpp']

src += [config.LIBCUTILS + '/system_properties.c']

event_sender_obj = com_env.Object(src)

Return('event_sender_obj')