Import('com_env')
#######################################################
# Compile for bootanimation
# Copyright Insta360 @ 2016 - 2025
#######################################################

import config

src = Glob('*.cpp')
src += [config.LIBCUTILS + '/system_properties.c']

event_sender_obj = com_env.Object(src)
Return('event_sender_obj')