####################################################################################################### 
# Copyright Insta360 @ 2016 - 2025
# Author:       Skymixos
# Date:         2018-07-25
# Version:      V0.1
# Description:  Compile for UI_SERVICE
#######################################################################################################

Import('com_env')

import config

src = ['MenuUI.cpp']
src += ['InputManager.cpp']
src += ['NetManager.cpp']
src += ['main.cpp']
src += ['NetlinkEvent.cpp']
src += ['NetlinkHandler.cpp']
src += ['NetlinkListener.cpp']
src += ['NetlinkManager.cpp']
src += ['SocketListener.cpp']
src += ['SocketClient.cpp']
src += ['VolumeManager.cpp']
src += ['ProtoManager.cpp']
src += ['TranManager.cpp']
src += ['CfgManager.cpp']
src += ['AudioManager.cpp']
src += ['HardwareService.cpp']
src += ['CacheService.cpp']

src += [config.UTIL + '/Process.cpp']
src += [config.UTIL + '/forkUtil.cpp']
src += [config.UTIL + '/ARMessage.cpp']
src += [config.UTIL + '/ARLooper.cpp']
src += [config.UTIL + '/bytes_int_convert.cpp']
src += [config.UTIL + '/util.cpp']
#src += [config.UTIL + '/cJSON.c']
src += [config.UTIL + '/http_util.cpp']
src += [config.UTIL + '/tinyxml2.cpp']


src += [config.UI_SERVICE + '/hw/oled_module.cpp']
src += [config.UI_SERVICE + '/hw/oled_light.cpp']
src += [config.UI_SERVICE + '/hw/bq40z50.cpp']

src += [config.UI_SERVICE + '/hw/ins_i2c.cpp']
src += [config.UI_SERVICE + '/hw/ins_gpio.cpp']

src += [config.LIBLOG + '/logd_write.c']
src += [config.LIBLOG + '/log_event_write.c']
src += [config.LIBLOG + '/logprint.c']
src += [config.LIBLOG + '/event_tag_map.c']
src += [config.LIBLOG + '/log_time.cpp']
src += [config.LIBLOG + '/log_wrapper.cpp']


src += [config.LIBCUTILS + '/system_properties.c']


com_env['CXXFLAGS'] += ' -I' + config.UI_SERVICE + '/include'
com_env['LINKFLAGS'] += '-L ' + config.UI_SERVICE 
com_env['LINKFLAGS'] += ' -lrt -lpthread -ljsoncpp'
UI_SERVICE_obj = com_env.Object(src)

Return('UI_SERVICE_obj')

