Import('com_env')
import config

src = Glob('*.cpp')
#src += Glob('*.c')


src += [config.LIBLOG + '/logd_write.c']
src += [config.LIBLOG + '/log_event_write.c']
src += [config.LIBLOG + '/logprint.c']
src += [config.LIBLOG + '/event_tag_map.c']
src += [config.LIBLOG + '/log_time.cpp']
src += [config.LIBLOG + '/log_wrapper.cpp']

src += [config.LIBCUTILS + '/system_properties.c']


com_env['CXXFLAGS'] += ' -I' + config.PRO2_SERVICE + '/include'
web_osc_obj = com_env.Object(src)

Return('web_osc_obj')

