Import('com_env')
import config

#src = Glob('*.cpp')
src = ['main.cpp']
src += ['web_http.cpp']
src += ['http_server.cpp']
src += ['UiListener.cpp']
src += ['EventServer.cpp']

src += [config.UI_SERVICE + '/SocketListener.cpp']
src += [config.UI_SERVICE + '/SocketClient.cpp']

src += [config.LIBLOG + '/logd_write.c']
src += [config.LIBLOG + '/log_event_write.c']
src += [config.LIBLOG + '/logprint.c']
src += [config.LIBLOG + '/event_tag_map.c']
src += [config.LIBLOG + '/log_time.cpp']
src += [config.LIBLOG + '/log_wrapper.cpp']

src += [config.LIBCUTILS + '/system_properties.c']

web_server_obj = com_env.Object(src)
Return('web_server_obj')

