Import('com_env')
#######################################################
# Compile for bootanimation
# Copyright Insta360 @ 2016 - 2025
#######################################################

import config

src = ['http_util.cpp']
src += ['simplest_web_test.cpp']
src += ['http_client.cpp']


src += [config.PRO2_SERVICE + '/util/arlog.c']
src += [config.PRO2_SERVICE + '/util/stlog.cpp']


src += [config.LIBLOG + '/logd_write.c']
src += [config.LIBLOG + '/log_event_write.c']
src += [config.LIBLOG + '/logprint.c']
src += [config.LIBLOG + '/event_tag_map.c']
src += [config.LIBLOG + '/log_time.cpp']

src += [config.LIBCUTILS + '/system_properties.c']

com_env['CXXFLAGS'] += ' -I' + config.PRO2_SERVICE + '/include'
http_server = com_env.Object(src)

Return('http_server')

