Import('com_env')
#######################################################
# Compile for bootanimation
# Copyright Insta360 @ 2016 - 2025
#######################################################

import config

src = Glob('*.cpp')
src += [config.UI_SERVICE + '/hw/ins_gpio.cpp']
src += [config.UI_SERVICE + '/hw/ins_i2c.cpp']
src += [config.UI_SERVICE + '/hw/oled_light.cpp']
src += [config.UI_SERVICE + '/hw/oled_module.cpp']
src += [config.UI_SERVICE + '/hw/battery_interface.cpp']

src += [config.UI_SERVICE + '/util/arlog.c']
src += [config.UI_SERVICE + '/util/stlog.cpp']
src += [config.UI_SERVICE + '/util/md5.cpp']
src += [config.UI_SERVICE + '/util/update_oled.cpp']
src += [config.UI_SERVICE + '/util/util.cpp']
src += [config.UI_SERVICE + '/forkUtil.cpp']

src += [config.LIBLOG + '/logd_write.c']
src += [config.LIBLOG + '/log_event_write.c']
src += [config.LIBLOG + '/logprint.c']
src += [config.LIBLOG + '/event_tag_map.c']
src += [config.LIBLOG + '/log_time.cpp']

src += [config.LIBCUTILS + '/system_properties.c']


com_env['CXXFLAGS'] += ' -I' + config.UI_SERVICE + '/include'
#com_env['LIBS'] += ['rt']
#com_env['LIBS'] += ['pthread']
update_app_obj = com_env.Object(src)

Return('update_app_obj')

