Import('com_env')
#######################################################
# Compile for bootanimation
# Copyright Insta360 @ 2016 - 2025
#######################################################

import config

src = Glob('*.cpp')
src += [config.UI_SERVICE + '/hw/oled_module.cpp']
src += [config.UI_SERVICE + '/hw/oled_light.cpp']
src += [config.UI_SERVICE + '/hw/battery_interface.cpp']
src += [config.UI_SERVICE + '/hw/ins_i2c.cpp']
src += [config.UI_SERVICE + '/hw/ins_gpio.cpp']


src += [config.UTIL + '/Process.cpp']
src += [config.UTIL + '/forkUtil.cpp']
src += [config.UTIL + '/md5.cpp']
src += [config.UTIL + '/update_oled.cpp']
src += [config.UTIL + '/update_util.cpp']
src += [config.UTIL + '/bytes_int_convert.cpp']
src += [config.UTIL + '/util.cpp']

src += [config.UI_SERVICE + '/NetlinkEvent.cpp']
src += [config.UI_SERVICE + '/NetlinkHandler.cpp']
src += [config.UI_SERVICE + '/NetlinkListener.cpp']
src += [config.UI_SERVICE + '/NetlinkManager.cpp']
src += [config.UI_SERVICE + '/SocketListener.cpp']
src += [config.UI_SERVICE + '/SocketClient.cpp']
src += [config.UI_SERVICE + '/VolumeManager.cpp']


src += [config.LIBLOG + '/logd_write.c']
src += [config.LIBLOG + '/log_event_write.c']
src += [config.LIBLOG + '/logprint.c']
src += [config.LIBLOG + '/event_tag_map.c']
src += [config.LIBLOG + '/log_time.cpp']
src += [config.LIBLOG + '/log_wrapper.cpp']


src += [config.LIBCUTILS + '/system_properties.c']



com_env['CXXFLAGS'] += ' -I' + config.UI_SERVICE + '/include'
#com_env['LIBS'] += ['rt']
#com_env['LIBS'] += ['pthread']
update_check_obj = com_env.Object(src)

Return('update_check_obj')

