Import('com_env')
#######################################################
# Compile for bootanimation
# Copyright Insta360 @ 2016 - 2025
#######################################################

import config

src = Glob('*.cpp')
src += [config.SYSTEM_SERVER + '/hw/oled_module.cpp']
src += [config.SYSTEM_SERVER + '/hw/ins_led.cpp']
src += [config.SYSTEM_SERVER + '/hw/ins_i2c.cpp']
src += [config.SYSTEM_SERVER + '/hw/ins_gpio.cpp']

src += [config.UTIL + '/Process.cpp']
src += [config.UTIL + '/forkUtil.cpp']
src += [config.UTIL + '/md5.cpp']
src += [config.UTIL + '/update_oled.cpp']
src += [config.UTIL + '/update_util.cpp']
src += [config.UTIL + '/bytes_int_convert.cpp']
src += [config.UTIL + '/util.cpp']

src += [config.SYSTEM_SERVER + '/NetlinkEvent.cpp']
src += [config.SYSTEM_SERVER + '/NetlinkHandler.cpp']
src += [config.SYSTEM_SERVER + '/NetlinkListener.cpp']
src += [config.SYSTEM_SERVER + '/NetlinkManager.cpp']
src += [config.SYSTEM_SERVER + '/SocketListener.cpp']
src += [config.SYSTEM_SERVER + '/SocketClient.cpp']
src += [config.SYSTEM_SERVER + '/VolumeManager.cpp']

src += [config.LIBLOG + '/logd_write.c']
src += [config.LIBLOG + '/log_event_write.c']
src += [config.LIBLOG + '/logprint.c']
src += [config.LIBLOG + '/event_tag_map.c']
src += [config.LIBLOG + '/log_time.cpp']
src += [config.LIBLOG + '/log_wrapper.cpp']


src += [config.LIBCUTILS + '/system_properties.c']

update_check_obj = com_env.Object(src)

Return('update_check_obj')

